# Accessing/Changing specific elements, roows, columns, etc

In [14]:
import numpy as np

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [16]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
#Get a specific element [r,c]
a[1,5]

13

In [18]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [20]:
#Getting a litle more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [21]:
#Change value
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [22]:
#Change entire column
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [23]:
#Change entire row
a[0,:] = 5
print(a)

[[ 5  5  5  5  5  5  5]
 [ 8  9  5 11 12 20 14]]


In [24]:
a[:,2] = [1,2]
print(a)

[[ 5  5  1  5  5  5  5]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [25]:
#[[[a,b],[a,b]],[[x,y],[x,y]]]
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
#Get specific element (work outside in)
b[0,1,1]

4

In [27]:
#Replace
b[:,1,:] = [[9,9],[8,8]]

In [28]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [29]:
#Replace
b[0,1,:] = [[9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.