# Initializing Different Types of Arrays

In [1]:
import numpy as np

In [5]:
#All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [10]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [12]:
#Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [17]:
#Initialize an array of random decimals
np.random.rand(4,2)

array([[0.67372751, 0.23386644],
       [0.5521798 , 0.20483172],
       [0.25094726, 0.55340462],
       [0.60572157, 0.95050722]])

In [23]:
#Random integer values
np.random.randint(4,8, size=(3,3))

array([[5, 6, 7],
       [4, 4, 5],
       [6, 5, 7]])

In [24]:
#Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays

In [39]:
a = np.array([1,2,3])
b = a.copy()
b

array([1, 2, 3])

In [40]:
b[0]= 100
print(b)

[100   2   3]


In [41]:
print(a)

[1 2 3]
