# Mathematics

In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a+2

array([3, 4, 5, 6])

In [12]:
a-2

array([-1,  0,  1,  2])

In [13]:
a*2

array([2, 4, 6, 8])

In [14]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [15]:
a+=2
a

array([3, 4, 5, 6])

In [16]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [17]:
a**2

array([ 9, 16, 25, 36])

In [18]:
#Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [19]:
#Take the cos
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

##### Linear Algebra

In [21]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [22]:
#Matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [23]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [24]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.min(stats, axis=1)

array([1, 4])

In [26]:
np.max(stats)

6

In [34]:
np.sum(stats, axis=0)

array([5, 7, 9])