# Reorganizing Arrays

In [1]:
import numpy as np

In [8]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([55,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[ 1,  2,  3,  4],
       [55,  6,  7,  8],
       [ 1,  2,  3,  4],
       [55,  6,  7,  8]])

In [13]:
#Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Load Data from file

In [29]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[1, 2, 3, 4, 2, 3, 4, 5, 6, 3, 4, 7, 8, 9, 6, 5, 4, 4, 6, 7],
       [3, 4, 5, 3, 4, 5, 6, 7, 5, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 5],
       [8, 7, 6, 5, 4, 3, 2, 1, 9, 8, 7, 0, 6, 5, 4, 3, 6, 8, 8, 6]])

##### Boolean Masking and Advanced Indexing

In [23]:
filedata > 5

array([[False, False, False, False, False, False, False, False,  True,
        False, False,  True,  True,  True,  True, False, False, False,
         True,  True],
       [False, False, False, False, False, False,  True,  True, False,
        False, False, False, False,  True,  True,  True,  True,  True,
         True, False],
       [ True,  True,  True, False, False, False, False, False,  True,
         True,  True, False,  True, False, False, False,  True,  True,
         True,  True]])

In [24]:
filedata[filedata>6]

array([7, 8, 9, 7, 7, 7, 8, 8, 8, 8, 8, 7, 9, 8, 7, 8, 8])

In [27]:
#You can index with a list in numpy
ls = np.array([1,2,3,4,5,6,7,8,9])
ls[[1,2,8]]

array([2, 3, 9])

In [30]:
#What columns have values greater than 5
np.any(filedata>5, axis=0)

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [35]:
((filedata>5) & (filedata<8))

array([[False, False, False, False, False, False, False, False,  True,
        False, False,  True, False, False,  True, False, False, False,
         True,  True],
       [False, False, False, False, False, False,  True,  True, False,
        False, False, False, False,  True,  True, False, False, False,
        False, False],
       [False,  True,  True, False, False, False, False, False, False,
        False,  True, False,  True, False, False, False,  True, False,
        False,  True]])

In [36]:
#Not
(~((filedata>5) & (filedata<8)))

array([[ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True, False,  True,  True,  True,
        False, False],
       [ True,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True],
       [ True, False, False,  True,  True,  True,  True,  True,  True,
         True, False,  True, False,  True,  True,  True, False,  True,
         True, False]])

In [37]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,34,35],[26,27,28,29,30]])
print(a)

a[]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 34 35]
 [26 27 28 29 30]]


In [38]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [48]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [52]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [34, 35],
       [29, 30]])